import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState, useEffect } from 'react';
// Added RefreshCw to imports
import { X, Phone, Video, Shield, Binary, Activity, Zap, Award, Loader2, RefreshCw } from 'lucide-react';
export const ModalWrapper = ({ onClose, title, children }) => (_jsx("div", { className: "fixed inset-0 z-[300] flex items-center justify-center p-3 md:p-6 backdrop-blur-xl bg-black/85 animate-in fade-in duration-300", children: _jsxs("div", { className: "w-full max-w-lg border-[0.5px] border-[#4caf50]/20 bg-[#0a1a0a]/95 p-6 md:p-10 relative overflow-hidden flex flex-col gap-6 shadow-[0_0_100px_rgba(0,0,0,0.95)] max-h-[95vh]", children: [_jsx("div", { className: "absolute top-0 left-0 w-full h-[1px] bg-gradient-to-r from-transparent via-[#00f3ff]/50 to-transparent" }), _jsxs("div", { className: "flex justify-between items-center border-b-[0.5px] border-[#4caf50]/10 pb-5 shrink-0", children: [_jsxs("div", { className: "flex flex-col gap-1", children: [_jsx("h3", { className: "orbitron text-[9px] md:text-sm font-black tracking-[0.2em] md:tracking-[0.4em] text-[#00f3ff] uppercase opacity-100", children: title }), _jsxs("span", { className: "text-[6px] text-[#4caf50] uppercase tracking-[0.3em] font-bold opacity-60", children: ["ISO_LINK_PARAMETER_0x", Math.floor(Math.random() * 256).toString(16).toUpperCase()] })] }), _jsx("button", { onClick: onClose, className: "text-[#4caf50] hover:text-[#00f3ff] transition-all p-2 bg-black/40 border-[0.5px] border-[#4caf50]/10 hover:border-[#00f3ff]/30 active:scale-90", children: _jsx(X, { size: 18, strokeWidth: 1.5 }) })] }), _jsx("div", { className: "flex-1 overflow-y-auto scrollbar-hide py-3", children: children }), _jsx("div", { className: "absolute top-2 left-2 w-3 h-3 border-t-[0.5px] border-l-[0.5px] border-[#00f3ff]/30" }), _jsx("div", { className: "absolute bottom-2 right-2 w-3 h-3 border-b-[0.5px] border-r-[0.5px] border-[#00f3ff]/30" })] }) }));
export const CallModal = ({ type, onClose }) => {
    const [status, setStatus] = useState('INITIATING_DTLS...');
    const [timer, setTimer] = useState(0);
    const [isSecure, setIsSecure] = useState(false);
    useEffect(() => {
        const s1 = setTimeout(() => setStatus('ESTABLISHING_SRTP_TUNNEL...'), 1200);
        const s2 = setTimeout(() => { setStatus('CONNECTED_ENCRYPTED_G3T'); setIsSecure(true); }, 2800);
        return () => { clearTimeout(s1); clearTimeout(s2); };
    }, []);
    useEffect(() => {
        if (isSecure) {
            const interval = setInterval(() => setTimer(t => t + 1), 1000);
            return () => clearInterval(interval);
        }
    }, [isSecure]);
    const formatTime = (s) => `${Math.floor(s / 60).toString().padStart(2, '0')}:${(s % 60).toString().padStart(2, '0')}`;
    return (_jsx(ModalWrapper, { title: `${type.toUpperCase()}_SESSION_ISO`, onClose: onClose, children: _jsxs("div", { className: "flex flex-col items-center gap-8 md:gap-12 py-8 md:py-14", children: [_jsxs("div", { className: "relative", children: [_jsx("div", { className: "absolute inset-0 bg-[#00f3ff]/5 blur-[60px] rounded-full animate-pulse" }), _jsxs("div", { className: `w-28 h-28 md:w-40 md:h-40 border-[0.5px] rounded-full flex items-center justify-center relative transition-all duration-1000 ${isSecure ? 'border-[#00f3ff] shadow-[0_0_30px_#00f3ff22] text-[#00f3ff]' : 'border-[#4caf50]/20 text-[#4caf50]/40 animate-pulse'}`, children: [type === 'voice' ? _jsx(Phone, { size: 44, strokeWidth: 0.5, className: "md:w-14 md:h-14" }) : _jsx(Video, { size: 44, strokeWidth: 0.5, className: "md:w-14 md:h-14" }), _jsx("div", { className: `absolute inset-0 border-[0.5px] rounded-full opacity-20 ${isSecure ? 'border-[#00f3ff] animate-ping' : 'border-[#4caf50]/40'}` }), isSecure && (_jsx("div", { className: "absolute -top-1 right-2 bg-black border-[0.5px] border-[#00f3ff] p-2 text-[#00f3ff] animate-in zoom-in duration-500 shadow-glow", children: _jsx(Shield, { size: 14, strokeWidth: 1 }) }))] })] }), _jsxs("div", { className: "text-center space-y-4 md:space-y-6", children: [_jsxs("div", { className: "flex flex-col gap-2", children: [_jsx("p", { className: `orbitron text-[8px] md:text-[11px] tracking-[0.4em] md:tracking-[0.6em] uppercase font-black ${isSecure ? 'text-[#00f3ff]' : 'text-[#4caf50] animate-pulse'}`, children: status }), _jsx("p", { className: "text-[6px] md:text-[8px] uppercase tracking-widest text-[#4caf50]/50 font-mono", children: "PEER: ISO_V_X9_TAUTOLOGY" })] }), isSecure ? (_jsxs("div", { className: "flex flex-col gap-2", children: [_jsx("p", { className: "font-mono text-2xl md:text-4xl text-[#00f3ff] font-black tracking-tighter shadow-glow", children: formatTime(timer) }), _jsx("span", { className: "text-[6px] text-[#00f3ff]/40 uppercase tracking-[0.5em] font-bold", children: "Bitrate: 512Kbps (AES_256)" })] })) : (_jsxs("div", { className: "flex items-center gap-3 justify-center text-[#4caf50]/30 italic font-black text-[9px] tracking-widest", children: [_jsx(Loader2, { size: 12, className: "animate-spin" }), " SYNCHRONIZING_CLOCKS..."] }))] }), _jsx("div", { className: "w-full max-w-[240px] pt-6", children: _jsx("button", { onClick: onClose, className: "w-full py-5 border-[0.5px] border-red-500/30 text-red-500 text-[9px] md:text-[11px] font-black tracking-[0.4em] uppercase hover:bg-red-500/10 transition-all active:scale-95 shadow-lg group", children: _jsx("span", { className: "opacity-80 group-hover:opacity-100", children: "TERMINATE_ISO_SESSION" }) }) })] }) }));
};
export const GroupModal = ({ onClose, onCreate }) => {
    const [name, setName] = useState('G3ZKP_MESH_01');
    const [securityLevel, setSecurityLevel] = useState(2);
    return (_jsx(ModalWrapper, { title: "INITIALIZE_MESH_NODE", onClose: onClose, children: _jsxs("div", { className: "space-y-10", children: [_jsxs("div", { className: "space-y-3", children: [_jsx("label", { className: "text-[7px] md:text-[8px] uppercase tracking-widest text-[#4caf50] font-black opacity-70", children: "Node_Designation_Label" }), _jsxs("div", { className: "relative", children: [_jsx("input", { type: "text", value: name, onChange: (e) => setName(e.target.value), placeholder: "MESH_ISO_...", className: "w-full bg-black/40 border-[0.5px] border-[#4caf50]/20 p-5 text-[11px] md:text-[13px] outline-none focus:border-[#00f3ff]/40 text-[#00f3ff] font-black tracking-widest uppercase transition-all" }), _jsx("div", { className: "absolute right-4 top-1/2 -translate-y-1/2 opacity-20", children: _jsx(Binary, { size: 14 }) })] })] }), _jsxs("div", { className: "space-y-4", children: [_jsx("p", { className: "text-[7px] md:text-[8px] uppercase tracking-widest text-[#4caf50] font-black opacity-70", children: "Cryptographic_Protocol_Tiers" }), _jsx("div", { className: "grid grid-cols-1 gap-3", children: [
                                { label: 'TAUTOLOGICAL_SOUNDNESS', icon: Shield, active: true },
                                { label: 'ISO_MAPPING_PERSISTENCE', icon: Zap, active: true },
                                { label: 'EPHEMERAL_GEODESIC_RATCHET', icon: RefreshCw, active: false }
                            ].map((p, i) => (_jsxs("div", { className: "flex justify-between items-center p-4 border-[0.5px] border-[#4caf50]/10 bg-black/20 group hover:border-[#00f3ff]/20 transition-all cursor-pointer", children: [_jsxs("div", { className: "flex items-center gap-4", children: [_jsx(p.icon, { size: 14, className: "text-[#4caf50]/40 group-hover:text-[#00f3ff]/40", strokeWidth: 1 }), _jsx("span", { className: "text-[8px] md:text-[10px] uppercase tracking-widest text-[#00f3ff]/80 font-black", children: p.label })] }), _jsx("div", { className: "w-10 h-5 bg-black border-[0.5px] border-[#4caf50]/20 relative shrink-0", children: _jsx("div", { className: `absolute top-1 left-1 w-3 h-3 transition-all ${p.active ? 'bg-[#00f3ff] translate-x-5 shadow-[0_0_8px_#00f3ff]' : 'bg-[#4caf50]/20'}` }) })] }, i))) })] }), _jsx("button", { onClick: () => onCreate?.(name), className: "w-full py-5 border-[0.5px] border-[#00f3ff]/50 text-[#00f3ff] font-black text-[10px] md:text-[12px] tracking-[0.5em] uppercase hover:bg-[#00f3ff]/10 transition-all active:scale-95 shadow-glow", children: "GENERATE_MESH_TX" })] }) }));
};
export const LicenseModal = ({ status, onClose }) => (_jsx(ModalWrapper, { title: "G3T_ISO_ECONOMICS", onClose: onClose, children: _jsxs("div", { className: "space-y-12", children: [_jsxs("div", { className: "p-8 border-[0.5px] border-[#00f3ff]/30 bg-[#00f3ff]/5 flex flex-col items-center gap-6 shadow-inner", children: [_jsxs("div", { className: "relative", children: [_jsx(Award, { size: 40, className: "text-[#00f3ff] animate-pulse", strokeWidth: 0.5 }), _jsx("div", { className: "absolute inset-0 border-[0.5px] border-[#00f3ff]/20 rounded-full scale-150 opacity-20" })] }), _jsxs("div", { className: "text-center", children: [_jsx("p", { className: "orbitron text-[10px] md:text-[12px] font-black text-[#00f3ff] tracking-[0.3em] uppercase", children: "TAUTOLOGY_GENESIS_LICENSE" }), _jsx("p", { className: "text-[8px] text-[#4caf50] mt-2 font-black uppercase opacity-60", children: "Status: PERSISTENT_GRADE_3" })] })] }), _jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "flex justify-between items-end", children: [_jsx("p", { className: "text-[8px] uppercase tracking-[0.3em] text-[#4caf50] font-black opacity-60", children: "PROOF_SOUNDNESS_CREDITS" }), _jsxs("p", { className: "text-[10px] font-mono font-black text-[#00f3ff] shadow-glow", children: [status.accumulatedValue.toFixed(1), " / 30.0"] })] }), _jsx("div", { className: "h-[3px] w-full bg-black border-[0.5px] border-[#4caf50]/10 overflow-hidden shadow-inner", children: _jsx("div", { className: "h-full bg-[#00f3ff] shadow-[0_0_20px_#00f3ff] transition-all duration-1000", style: { width: `${(status.accumulatedValue / 30) * 100}%` } }) }), _jsxs("div", { className: "flex items-center gap-3 text-[7px] text-[#4caf50]/40 font-mono italic leading-relaxed uppercase tracking-widest text-center justify-center", children: [_jsx(Activity, { size: 10, strokeWidth: 1 }), " AUTO_RENEW_ENABLED_CYCLE_V1.1"] })] }), _jsxs("div", { className: "grid grid-cols-2 gap-4", children: [_jsx("button", { className: "py-4 border-[0.5px] border-[#4caf50]/10 text-[8px] font-black tracking-widest uppercase opacity-20 cursor-not-allowed", children: "RENEW" }), _jsx("button", { className: "py-4 border-[0.5px] border-[#00f3ff]/40 text-[#00f3ff] text-[8px] font-black tracking-widest uppercase hover:bg-[#00f3ff]/10 transition-all active:scale-95 shadow-glow", children: "TOP_UP_G3T_ISO" })] })] }) }));
export const SettingsModal = ({ onClose }) => (_jsx(ModalWrapper, { title: "CORE_NODE_PARAMETERS", onClose: onClose, children: _jsxs("div", { className: "space-y-10", children: [[
                { title: 'GEODESIC_LINK', items: ['Protocol: Tautology_3.1', 'Theme: Geodesic_Deep'] },
                { title: 'SECURITY_VAULT', items: ['ZKP_Soundness: Supreme', 'Stealth_Ratchet: ON'] },
                { title: 'NETWORK_ISO', items: ['GossipSub: Active', 'Mesh_Topology: Isomorphic'] }
            ].map((section, idx) => (_jsxs("div", { className: "space-y-5", children: [_jsxs("div", { className: "flex items-center gap-4", children: [_jsx("span", { className: "text-[9px] font-black text-[#4caf50] tracking-[0.3em] uppercase opacity-80 shrink-0", children: section.title }), _jsx("div", { className: "flex-1 h-[0.5px] bg-[#4caf50]/10" })] }), _jsx("div", { className: "space-y-4", children: section.items.map((item, i) => (_jsxs("div", { className: "flex justify-between items-center text-[10px] text-[#00f3ff]/70 font-mono py-2 bg-black/20 px-3 border-l-[1px] border-[#4caf50]/10 hover:border-[#00f3ff]/40 transition-all group", children: [_jsx("span", { className: "truncate pr-4 uppercase tracking-tighter group-hover:tracking-normal transition-all", children: item }), _jsx("span", { className: "text-[#4caf50]/40 cursor-pointer hover:text-[#00f3ff] transition-all uppercase text-[7px] font-black shrink-0", children: "ADJUST" })] }, i))) })] }, idx))), _jsxs("div", { className: "pt-6 border-t-[0.5px] border-[#4caf50]/10 flex flex-col items-center gap-2", children: [_jsx("p", { className: "text-[7px] uppercase font-mono opacity-20 tracking-tighter truncate max-w-full", children: "NODE_HASH: 0xG3T_ISO_ARCHITECT_CORE_v1.0.99XF" }), _jsxs("div", { className: "flex gap-4 opacity-10", children: [_jsx(Binary, { size: 10 }), " ", _jsx(Activity, { size: 10 }), " ", _jsx(Zap, { size: 10 })] })] })] }) }));
